# Generated by Django 5.0.1 on 2024-01-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_image',
            field=models.FileField(db_index=True, null=True, upload_to='product_image'),
        ),
    ]
