# Generated by Django 5.0.1 on 2024-01-18 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0005_customers_auth_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(db_index=True, max_length=100, null=True)),
                ('status', models.CharField(db_index=True, max_length=100, null=True)),
                ('total_count', models.CharField(db_index=True, max_length=100, null=True)),
                ('address', models.TextField(db_index=True, null=True)),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_order_id', to='customerapp.customers')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_order_id', to='customerapp.products')),
            ],
        ),
    ]
